### ISSUE TITLE
We are getting following issue for more connected graphs 

### ISSUE THREAD

**Issue by alex124585** [TensorBFS/OMEinsumContractionOrders.jl#36]
Getting pace complexity not found and then Julia thread gets killed
┌ Warning: target space complexity not found, got: 34.0, with time complexity 45.65477344005592, read-write complexity 36.76159466700723.
└ @ OMEinsumContractionOrders ~/.julia/packages/OMEinsumContractionOrders/dbGto/src/treesa.jl:229
./run_julia_degeneracy.sh: line 5:  7718 Killed                  /opt/omniai/work/instance1/jupyter/environment/applications/builds/julia-1.8.5/bin/julia --threads 8 julia_scripts/run_degeneracy.jl $L 0.8 $r 0 $seed

**Comment by GiggleLiu** [comment]
Do you mind pasting the code here? It is just a warning that contracting the tensor will create too large intermediate tensor size. You may want to check the memory usage of your computer while running the script.

**Comment by GiggleLiu** [comment]
Close for being unable to reproduce the issue.
