### ISSUE TITLE
Data Convertor between TreeWidthSolver.jl and OMEinsumContractionOrder.jl

### ISSUE THREAD

**Issue by ArrogantGao** [TensorBFS/OMEinsumContractionOrders.jl#42]
Plan to add a backend using tree decomposition, which will be provided in TreeWidthSlover.jl.
A data convertor between OMEinsumContractionOrder.jl and TreeWidthSlover.jl, to convent tensor networks as graphs and to convert tree decomposition as contraction order, should be added in the future.

**Comment by ArrogantGao** [comment]
The TreeWidthSlover.jl now work as a backend of the optimizer `ExactTreeWidth()`, see #43

**Comment by GiggleLiu** [comment]
Fixed by #43
